import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <header>
        <ul>
          <li>oi</li>
          <li>oi</li>
        </ul>
        </header>
        {children}
      </body>
    </html>
  );
}
